import type { IBlogCard } from "./components/types";

export const cardArray: IBlogCard[] = [
  {
    id: 1 ,
    name: "Toby",
    ubication: 'Lomas de Zamora',
    image: "",
    description: "ver detalle",
    state: '',
    isNew: true,
  },
  {
    id: 2,
    name: "Fito",
    ubication: 'San Vicente',
    image: undefined,
    description: "ver detalle",
    state: '',
  },
  {
    id: 3,
    name: "Rocky",
    ubication: 'Escobar',
    image: undefined,
    description: "ver detalle",
    state: '',
  },
  {
    id: 4,
    name: "Hercules",
    ubication: 'CABA - Flores',
    image: undefined,
    description: "ver detalle",
    state: '',
  },
  {
    id: 5,
    name: "Pini",
    ubication: 'Retiro',
    image: undefined,
    description: "ver detalle",
    state: '',
  },
  {
    id: 6,
    name: "Simon",
    ubication: 'Lincoln',
    image: undefined,
    description: "ver detalle",
    state: '',
  },
  {
    id: 7,
    name: "Sasha",
    ubication: 'San Justo',
    image: undefined,
    description: "ver detalle",
    state: '',
  },
  {
    id: 8,
    name: "Tolueno",
    ubication: 'San Justo',
    image: undefined,
    description: "ver detalle",
    state: '',
  },
  // {
  //   id: 9,
  //   name: "Baltazar",
  //   ubication: 'San Justo',
  //   image: undefined,
  //   description: "ver detalle",
  //   state: '',
  // },
  // {
  //   id: 10,
  //   name: "Indiana",
  //   ubication: 'San Justo',
  //   image: undefined,
  //   description: "ver detalle",
  //   state: '',
  // },
  {
    id: 11,
    name: "Simétrico",
    ubication: 'San Justo',
    image: undefined,
    description: "ver detalle",
    state: '',
  },
];

export const mockNewItem: IBlogCard = {
  id: 0,
  name: "New Item",
  ubication: 'Test click ubication',
  description: "Test click event",
  state: '',
  image: "",
  isNew: false,
};
